reverseProxy:
    image: neo4j/helm-charts-reverse-proxy:5.12.0
    serviceName: "my-neo4j-admin"
    ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        tls:
            enabled: true
            config:
                - secretName: tls-secret
                  hosts:
                    - test.akstest.tech