apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
mountOptions: []
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
