---
version: '2'
services:

  connect:
    image: confluentinc/cp-kafka-connect-base:6.0.1
    hostname: connect
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:

      # CONNECT_TOPIC_CREATION_ENABLE: "true"
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_CUB_KAFKA_TIMEOUT: 300
      CONNECT_BOOTSTRAP_SERVERS: 'pkc-56d1g.eastus.azure.confluent.cloud:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: https://psrc-jxv6q.uaenorth.azure.confluent.cloud
      CONNECT_KEY_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: "USER_INFO"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: "EMSAOLNBWC7KBX2X:iRIfKMdSWGkNkS8Ht93jDb015HpnWvVPoDD0a1005DvasKHmtL8YyvjSBI4RRvnn"
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: https://psrc-jxv6q.uaenorth.azure.confluent.cloud
      CONNECT_VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: "USER_INFO"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: "EMSAOLNBWC7KBX2X:iRIfKMdSWGkNkS8Ht93jDb015HpnWvVPoDD0a1005DvasKHmtL8YyvjSBI4RRvnn"
      # CLASSPATH required due to CC-2422
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      CONNECT_PLUGIN_PATH: /usr/share/java, /usr/share/confluent-hub-components, /data/connect-jars

      CONNECT_REQUEST_TIMEOUT_MS: "20000"
      CONNECT_RETRY_BACKOFF_MS: "500"
      CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      CONNECT_SASL_MECHANISM: "PLAIN"
      CONNECT_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"EMSAOLNBWC7KBX2X\" password=\"iRIfKMdSWGkNkS8Ht93jDb015HpnWvVPoDD0a1005DvasKHmtL8YyvjSBI4RRvnn\";"

      CONNECT_CONSUMER_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_CONSUMER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      CONNECT_CONSUMER_SASL_MECHANISM: "PLAIN"
      CONNECT_CONSUMER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"EMSAOLNBWC7KBX2X\" password=\"iRIfKMdSWGkNkS8Ht93jDb015HpnWvVPoDD0a1005DvasKHmtL8YyvjSBI4RRvnn\";"
      CONNECT_CONSUMER_REQUEST_TIMEOUT_MS: "20000"
      CONNECT_CONSUMER_RETRY_BACKOFF_MS: "500"
      #
      CONNECT_PRODUCER_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      CONNECT_PRODUCER_SASL_MECHANISM: "PLAIN"
      CONNECT_PRODUCER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"EMSAOLNBWC7KBX2X\" password=\"iRIfKMdSWGkNkS8Ht93jDb015HpnWvVPoDD0a1005DvasKHmtL8YyvjSBI4RRvnn\";"
      CONNECT_PRODUCER_REQUEST_TIMEOUT_MS: "20000"
      CONNECT_PRODUCER_RETRY_BACKOFF_MS: "500"

    volumes:
        - /home/new/data:/data
        - /home/new/plugins:/usr/share/confluent-hub-components

    command:
      - bash
      - -c
      - |
        /etc/confluent/docker/run &
        echo "done"
        #
        #
        sleep infinity
