configuration:
  kestra:
    queue:
      type: postgres
    repository:
      type: postgres
    storage:
      type: azure
      azure:
        container: "backups"
        endpoint: "https://hacnpgpsab33ozt6h.blob.core.windows.net/"
        connectionString: "DefaultEndpointsProtocol=https;AccountName=hacnpgpsab33ozt6h;AccountKey=Q2c3rjcqZmZWjXxWy0u2cEciEEQvEp6mdOQwx0RrzsMNC0DaeuPOsvIDfGNhnQD9yyHhJ6vVSQN/+AStZFDKVw==;EndpointSuffix=core.windows.net"

  datasources:
    postgres:
      url: jdbc:postgresql://20.171.241.80:5432/kestra_db  # Change database from 'template1' to 'kestra'
      driverClassName: org.postgresql.Driver
      username: app
      password: XiuZzlNIOsne+pNfh7GpIg==

postgresql:
  enabled: false  # Ensure an external PostgreSQL is running

minio:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: kestra.morecloudprivate.shop
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: chart-example-tls
      hosts:
        - kestra.morecloudprivate.shop
