apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: debezium-cluster
  namespace: debezium-example
spec:
  kafka:
    replicas: 1 #use this to add and remove number of brokers
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
      # - name: external2
      #   port: 9095
      #   type: ingress
      #   tls: true
      #   authentication:
      #     type: tls
      #   configuration:
      #     class: nginx
      #     bootstrap:
      #       host: test.akstest.tech
      #     brokers:
      #     - broker: 0
      #       host: broker-0.akstest.tech

    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
    config:
      auto.create.topics.enable: true
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      delete.topic.enable: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
