apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: mysql-source-connector
  namespace: confluent
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  taskMax: 1
  configs:
    database.hostname: 4.240.87.220
    database.port: "3306"
    database.user: debezium
    database.password: dbz
    database.server.id: "184054"
    topic.prefix: mysql
    database.include.list: inventory
    schema.history.internal.kafka.topic: schema-changes.inventory
    schema.history.internal.kafka.bootstrap.servers: kafka-0-internal.confluent.svc.cluster.local:9092
    include.schema.changes: "true"
  connectClusterRef:
    name: connect
    namespace: confluent
