apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: temp-deployment
  template:
    metadata:
      labels:
        app: temp-deployment
    spec:
      containers:
      - name: temp-deployment
        image: amitgujar/static-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

